name : validate

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.1"
    - run: pip install --upgrade pip
    - run: pip install "black<23" pylint mypy
    
    - name: PyLint
      run: pylint $(git ls-files '*.py') --fail-under=7

    - name: Black
      run: black --diff --check $(git ls-files '*.py')

    - name: MyPy
      run: mypy $(git ls-files '*.py')