name : validate

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.11.1"
    - run: pip install --upgrade pip
    - run: pip install "black<23" pylint mypy
    - run: pylint $(git ls-files '*.py')
    - run: mypy $(git ls-files '*.py')
    - run: black --diff --check $(git ls-files '*.py')
